from __future__ import annotations

from dataclasses import dataclass
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader

from .utils import WindowMetadata


@dataclass(frozen=True)
class WindowSplit:
    """
    Represents a processed subset of data (e.g., just Training, or just Validation).
    Generated by the WindowBuilder acting on a single list of DataFrames.
    """
    # Tensors
    y: np.ndarray  # (N, seq_len, 1)
    c: np.ndarray  # (N, seq_len, n_cond)

    # PyTorch Loader
    loader: DataLoader

    # Metadata & Reconstruction Info
    metadata: list[WindowMetadata]
    templates: dict[str, pd.DataFrame]

    def __len__(self) -> int:
        return self.y.shape[0]


@dataclass(frozen=True)
class ConditionalWindowPack:
    """
    The final container that holds the Train Split and Val Split together.
    This is what the Trainer expects.
    """
    train_split: WindowSplit
    val_split: WindowSplit

    # Global Schema Info
    target_col: str
    cond_cols: list[str]
    scaling_params: dict[str, tuple[float, float]] | None

    # Properties for backward compatibility with Trainer
    @property
    def y_train(self) -> np.ndarray: return self.train_split.y

    @property
    def c_train(self) -> np.ndarray: return self.train_split.c

    @property
    def y_val(self) -> np.ndarray: return self.val_split.y

    @property
    def c_val(self) -> np.ndarray: return self.val_split.c

    @property
    def meta_val(self) -> list[WindowMetadata]: return self.val_split.metadata

    @property
    def val_templates(self) -> dict[str, pd.DataFrame]: return self.val_split.templates

    @property
    def train_templates(self) -> dict[str, pd.DataFrame]: return self.train_split.templates

    @property
    def meta_train(self) -> list[WindowMetadata]: return self.train_split.metadata

    def get_summary(self) -> str:
        return (
            f"WindowPack Summary:\n"
            f"  - Train Windows: {len(self.train_split)}\n"
            f"  - Val Windows:   {len(self.val_split)}\n"
            f"  - Features:      {len(self.cond_cols)}"
        )