from __future__ import annotations

from dataclasses import dataclass
import numpy as np
import pandas as pd
from torch.utils.data import DataLoader

from .utils import WindowMetadata


@dataclass
class WindowSplit:
    """
    Represents a processed subset of data (e.g., just Training, or just Validation).
    Generated by the WindowBuilder acting on a single list of DataFrames.
    """
    # Tensors
    y: np.ndarray  # (N, seq_len, 1)
    c_dynamic: np.ndarray  # (N, seq_len, n_cond)
    c_static: np.ndarray # (N, n_stat)

    # Reconstruction info
    dynamic_cols_indices: list[int]
    static_cols_indices: list[int]
    n_total_cond: int

    # PyTorch Loader
    loader: DataLoader

    # Metadata & Reconstruction Info
    metadata: list[WindowMetadata]
    templates: dict[str, pd.DataFrame]

    def __len__(self) -> int:
        return self.y.shape[0]

    @property
    def c(self) -> np.ndarray:
        """
        Reconstructs the full (N, seq_len, n_cond) matrix on the fly.
        Useful for reconstruction/visualization without storing the redundancy.
        """
        N, seq_len, _ = self.c_dynamic.shape

        # 1. Create an empty container
        full_c = np.empty((N, seq_len, self.n_total_cond), dtype=np.float32)

        # 2. Fill in dynamic values
        if self.dynamic_cols_indices:
            full_c[:, :, self.dynamic_cols_indices] = self.c_dynamic

        # 3. Fill in static values (Broadcasting)
        # c_static is (N, n_stat) -> gets repeated for the whole sequence
        if self.static_cols_indices:
            # Expand dims: (N, 1, n_stat) -> (N, seq_len, n_stat)
            static_expanded = np.expand_dims(self.c_static, axis=1)
            static_broadcasted = np.repeat(static_expanded, seq_len, axis=1)

            full_c[:, :, self.static_cols_indices] = static_broadcasted

        return full_c


@dataclass(frozen=True)
class ConditionalWindowPack:
    """
    The final container that holds the Train Split and Val Split together.
    This is what the Trainer expects.
    """
    train_split: WindowSplit
    val_split: WindowSplit

    # Global Schema Info
    target_col: str
    cond_cols: list[str]
    scaling_params: dict[str, tuple[float, float]] | None

    # Properties for backward compatibility with Trainer
    @property
    def y_train(self) -> np.ndarray: return self.train_split.y

    @property
    def c_train(self) -> np.ndarray: return self.train_split.c

    @property
    def y_val(self) -> np.ndarray: return self.val_split.y

    @property
    def c_val(self) -> np.ndarray: return self.val_split.c

    @property
    def meta_val(self) -> list[WindowMetadata]: return self.val_split.metadata

    @property
    def val_templates(self) -> dict[str, pd.DataFrame]: return self.val_split.templates

    @property
    def train_templates(self) -> dict[str, pd.DataFrame]: return self.train_split.templates

    @property
    def meta_train(self) -> list[WindowMetadata]: return self.train_split.metadata

    def get_summary(self) -> str:
        return (
            f"WindowPack Summary:\n"
            f"  - Train Windows: {len(self.train_split)}\n"
            f"  - Val Windows:   {len(self.val_split)}\n"
            f"  - Features:      {len(self.cond_cols)}"
        )