"""Reimplement TimeGAN-pytorch Codebase.

Reference: Jinsung Yoon, Daniel Jarrett, Mihaela van der Schaar,
"Time-series Generative Adversarial Networks,"
Neural Information Processing Systems (NeurIPS), 2019.

Paper link: https://papers.nips.cc/paper/8789-time-series-generative-adversarial-networks

Last updated Date: October 18th 2021
Code author: Zhiwei Zhang (bitzzw@gmail.com), Biaolin Wen (robinbg@foxmail.com)

-----------------------------

model.py: Network Modules

(1) Encoder
(2) Recovery
(3) Generator
(4) Supervisor
(5) Discriminator
"""

import torch.nn as nn
import torch.nn.init as init


def _weights_init(m):
    classname = m.__class__.__name__
    if isinstance(m, nn.Linear):
        init.xavier_uniform_(m.weight)
        m.bias.data.fill_(0)
    elif classname.find('Conv') != -1:
        m.weight.data.normal_(0.0, 0.02)
    elif classname.find('Norm') != -1:
        m.weight.data.normal_(1.0, 0.02)
        m.bias.data.fill_(0)
    elif classname.find("GRU") != -1:
        for name, param in m.named_parameters():
            if 'weight_ih' in name:
                init.xavier_uniform_(param.data)
            elif 'weight_hh' in name:
                init.orthogonal_(param.data)
            elif 'bias' in name:
                param.data.fill_(0)


class Encoder(nn.Module):
    """Embedding network between original feature space to latent space.

        Args:
          - input: input time-series features. (N, L, X) = (24, ?, 6)
          - h3: (num_layers, N, H). [3, ?, 24]

        Returns:
          - H: embeddings
        """

    def __init__(
            self,
            z_dim: int,
            hidden_dim: int,
            num_layers: int = 1,
    ):
        super(Encoder, self).__init__()
        self.rnn = nn.GRU(input_size=z_dim, hidden_size=hidden_dim, num_layers=num_layers, batch_first=True)
        # self.norm = nn.BatchNorm1d(opt.hidden_dim)
        self.fc = nn.Linear(hidden_dim, hidden_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        e_outputs, _ = self.rnn(input)
        H = self.fc(e_outputs)
        if sigmoid:
            H = self.sigmoid(H)
        return H


class Recovery(nn.Module):
    """Recovery network from latent space to original space.

    Args:
      - H: latent representation
      - T: input time information

    Returns:
      - X_tilde: recovered data
    """

    def __init__(
            self,
            z_dim: int,
            hidden_dim: int,
            num_layers: int = 1,
    ):
        super(Recovery, self).__init__()
        self.rnn = nn.GRU(input_size=hidden_dim, hidden_size=z_dim, num_layers=num_layers, batch_first= True)

        #  self.norm = nn.BatchNorm1d(opt.z_dim)
        self.fc = nn.Linear(z_dim, z_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        r_outputs, _ = self.rnn(input)
        X_tilde = self.fc(r_outputs)
        if sigmoid:
            X_tilde = self.sigmoid(X_tilde)
        return X_tilde


class Generator(nn.Module):
    """Generator function: Generate time-series data in latent space.

    Args:
      - Z: random variables
      - T: input time information

    Returns:
      - E: generated embedding
    """

    def __init__(
            self,
            z_dim: int,
            hidden_dim: int,
            num_layers: int = 1,
    ):
        super(Generator, self).__init__()
        self.rnn = nn.GRU(input_size=z_dim, hidden_size=hidden_dim, num_layers=num_layers, batch_first=True)
        # self.norm = nn.LayerNorm(opt.hidden_dim)
        self.fc = nn.Linear(hidden_dim, hidden_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        g_outputs, _ = self.rnn(input)
        #  g_outputs = self.norm(g_outputs)
        E = self.fc(g_outputs)
        if sigmoid:
            E = self.sigmoid(E)
        return E


class Supervisor(nn.Module):
    """Generate next sequence using the previous sequence.

    Args:
      - H: latent representation
      - T: input time information

    Returns:
      - S: generated sequence based on the latent representations generated by the generator
    """

    def __init__(
            self,
            hidden_dim: int,
            num_layers: int = 1,
    ):
        super(Supervisor, self).__init__()
        self.rnn = nn.GRU(input_size=hidden_dim, hidden_size=hidden_dim, num_layers=num_layers, batch_first=True)
        # self.norm = nn.LayerNorm(opt.hidden_dim)
        self.fc = nn.Linear(hidden_dim, hidden_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        s_outputs, _ = self.rnn(input)
        #  s_outputs = self.norm(s_outputs)
        S = self.fc(s_outputs)
        if sigmoid:
            S = self.sigmoid(S)
        return S


class Discriminator(nn.Module):
    """Discriminate the original and synthetic time-series data.

    Args:
      - H: latent representation
      - T: input time information

    Returns:
      - Y_hat: classification results between original and synthetic time-series
    """

    def __init__(
            self,
            hidden_dim: int,
            num_layers: int = 1,
    ):
        super(Discriminator, self).__init__()
        self.rnn = nn.GRU(input_size=hidden_dim, hidden_size=hidden_dim, num_layers=num_layers, batch_first=True)
        #  self.norm = nn.LayerNorm(opt.hidden_dim)
        self.fc = nn.Linear(hidden_dim, hidden_dim)
        self.sigmoid = nn.Sigmoid()
        self.apply(_weights_init)

    def forward(self, input, sigmoid=True):
        d_outputs, _ = self.rnn(input)
        Y_hat = self.fc(d_outputs)
        if sigmoid:
            Y_hat = self.sigmoid(Y_hat)
        return Y_hat

class TimeGan(nn.Module):
    """
    Pure TimeGAN networks: Encoder, Recovery, Generator,
    Supervisor, Discriminator.
    """

    def __init__(
        self,
        encoder_input_dim: int,
        hidden_dim: int,
        generator_input_dim: int,
        recovery_output_dim: int,
        num_layers: int = 1,
    ) -> None:
        super().__init__()
        self.encoder = Encoder(
            z_dim=encoder_input_dim,
            hidden_dim=hidden_dim,
            num_layers=num_layers,
        )
        self.recovery = Recovery(
            hidden_dim=hidden_dim,
            z_dim=recovery_output_dim,
            num_layers=num_layers,
        )
        self.generator = Generator(
            z_dim=generator_input_dim,
            hidden_dim=hidden_dim,
            num_layers=num_layers,
        )
        self.supervisor = Supervisor(
            hidden_dim=hidden_dim,
            num_layers=num_layers,
        )
        self.discriminator = Discriminator(
            hidden_dim=hidden_dim,
            num_layers=num_layers,
        )

    def e_forward(self, x):
        return self.encoder(x)

    def r_forward(self, H):
        return self.recovery(H)

    def s_forward(self, H):
        return self.supervisor(H)

    def g_forward(self, z_input):
        return self.generator(z_input)

    def d_forward(self, H):
        return self.discriminator(H)
